# Generated by Django 5.1.2 on 2024-12-27 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cardbodies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.IntegerField(auto_created=True, verbose_name='Photo ID')),
                ('photo', models.FileField(upload_to='albums/', verbose_name='Photo')),
                ('photo_caption', models.TextField(verbose_name='Photo Caption')),
                ('cardbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cardbodies')),
            ],
            options={
                'ordering': ['photo_caption'],
            },
        ),
    ]
