# Generated by Django 5.1.2 on 2024-12-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbodies',
            name='photo',
        ),
    ]
