# Generated by Django 5.1.2 on 2024-12-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_cardbodies_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cardbody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='index.cardbodies'),
        ),
    ]
