# Generated by Django 5.1.2 on 2025-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_album_options_colorchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbodies',
            name='brand',
            field=models.CharField(default='Easy Wearr', max_length=255, verbose_name='Brand'),
            preserve_default=False,
        ),
    ]
